name: Deploy to Firebase functions

on:
  push:
    branches: [ "main" ]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: install firsebase cli
        run: npm install -g firebase-tools
      
      - name: build
        env: 
          REACT_APP_FIREBASE_PROJECT_ID: ${{ vars.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_API_KEY: ${{ vars.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ vars.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ vars.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ vars.REACT_APP_FIREBASE_APP_ID }}

        run: CI=false npm run build


      - name: Deploy to hosting and functions
        run: firebase deploy --only hosting, functions --token ${{ sectrets.FIREBASE_TOKEN }} --project dev --force

      
